global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['cliniq_prometheus:9090']

  - job_name: 'cliniq_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['cliniq_api:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cliniq_cadvisor:8080']